services:
  - type: web
    name: hunterxjobs-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRATION
        value: 24h
      - key: USE_MOCK_DATA
        value: true
      - key: FRONTEND_URL
        value: https://xlieu.github.io/HunterxJobs-Website 